name: 'Scala Snippet Checker'
description: 'Run Scala code from snippet in issues'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}
  max-lines: 
    description: If the output of the running snippet code is longer than `max-lines`, it will not be fully displayed in comment.
    default: 10  
runs:
  using: 'node12'
  main: 'dist/index.js'
